// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  mainSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
      ],
    },
    {
      type: 'category',
      label: 'Foundations',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'foundations/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'foundations',
        },
      ],
    },
    {
      type: 'category',
      label: 'Design',
      collapsed: true,
        type: 'doc',
        id: 'design/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'design',
        },
      ],
    },
    {
      type: 'category',
      label: 'Contracts',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Contracts',
        description: 'Contracts documentation for all Compose facets and libraries.',
        keywords: ['contracts', 'facets', 'libraries', 'solidity'],
      },
      items: [
        {
          type: 'category',
          label: 'Facets',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'contracts/facets/index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'contracts/facets',
            },
          ], 
        },
        {
          type: 'category',
          label: 'Libraries',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'contracts/libraries/index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'contracts/libraries',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Contribution',
      items: [
        {
          type: 'autogenerated',
          dirName: 'contribution',
        },
      ],
    },
  ],
};

export default sidebars;
